**4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.**

In [1]:
import numpy as np
import time

# Problem 1 — Array Creation

**1. Empty array (2×2)**

In [ ]:
a = np.empty((2,2))   # creates uninitialized array
print(a)


[[ 2.32905600e-315  0.00000000e+000]
 [-9.48664815e+250  4.50131211e-072]]


**2. All-ones array (4×2)**

In [ ]:
b = np.ones((4,2))
print(b)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**3. New array filled with a value**

In [ ]:
c = np.full((3,3), 7)   # 3x3 filled with 7
print(c)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


**4. Zeros array with same shape/type as given array**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
d = np.zeros_like(arr)
print(d)


[[0 0 0]
 [0 0 0]]


**5. Ones array with same shape/type**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
e = np.ones_like(arr)
print(e)


[[1 1 1]
 [1 1 1]]


**6. Convert list to numpy array**

In [ ]:
new_list = [1,2,3,4]
f = np.array(new_list)
print(f)


[1 2 3 4]


# Problem 2 — Array Manipulation & Indexing

**1. Array from 10 to 49**

In [ ]:
a = np.arange(10, 50)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**2. 3×3 matrix with values 0–8**

In [ ]:
b = np.arange(9).reshape(3,3)
print(b)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. 3×3 Identity matrix**

In [ ]:
c = np.eye(3)
print(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Random array of size 30 + mean**

In [ ]:
d = np.random.random(30)
print("Mean =", d.mean())


Mean = 0.48364291278030735


**5. 10×10 random array → min & max**

In [ ]:
e = np.random.random((10,10))
print("Min =", e.min())
print("Max =", e.max())


Min = 0.001808916951756001
Max = 0.9911802738355616


**6. Zero array of size 10, replace 5th element with 1**

In [ ]:
f = np.zeros(10)
f[4] = 1   # index 4 = 5th element
print(f)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array**

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])


[0 4 0 0 2 1]


**8. 2D array with 1 on border and 0 inside**

In [ ]:
g = np.ones((5,5))   # change size as needed
g[1:-1, 1:-1] = 0
print(g)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**9. 8×8 checkerboard pattern**

In [ ]:
h = np.zeros((8,8))
h[1::2, ::2] = 1
h[::2, 1::2] = 1
print(h)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# Problem 3 — Array Operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])


**1. Add arrays**

In [ ]:
print(x + y)


[[ 6  8]
 [10 13]]


**2. Subtract arrays**

In [ ]:
print(x - y)


[[-4 -4]
 [-4 -3]]


**3. Multiply array with integer**

In [ ]:
print(x * 3)


[[ 3  6]
 [ 9 15]]


**4. Square of each element**

In [ ]:
print(np.square(x))


[[ 1  4]
 [ 9 25]]


**5. Dot products**

In [ ]:
print("v·w =", np.dot(v,w))
print("x·v =", np.dot(x,v))
print("x·y =", np.dot(x,y))


v·w = 219
x·v = [29 77]
x·y = [[19 22]
 [50 58]]


**6. Concatenate x & y (rows), and v & w (columns)**

In [ ]:
print(np.concatenate((x,y), axis=0))  # row-wise

print(np.vstack((v,w)))  # column-wise


[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


**7. Concatenate x and v → ERROR**

In [ ]:
np.concatenate((x, v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Problem 4 — Matrix Operations

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


**1. Prove A·A⁻¹ = I**

In [ ]:
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


**2. Prove AB ≠ BA**

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
if np.array_equal(np.dot(A, B), np.dot(B, A)):
    print("False")
else:
    print("True")

True


**3. Prove (AB)ᵀ = Bᵀ Aᵀ**

In [ ]:
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))
print(left)
print(right)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


**2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9**


**Matrix form AX = B**

In [ ]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])


**Solution using inverse**

In [ ]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution = ", X)


Solution =  [ 2.  1. -2.]


# Problem 5 — How Fast is NumPy?

In [ ]:
import time
import numpy as np

**1. Element-wise Addition**

Using Python List

In [ ]:
L1 = list(range(1_000_000))
L2 = list(range(1_000_000))

start = time.time()
L3 = [L1[i] + L2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Time =", end-start)


Python List Time = 0.10238766670227051


Using NumPy

In [ ]:
A1 = np.arange(1_000_000)
A2 = np.arange(1_000_000)

start = time.time()
A3 = A1 + A2
end = time.time()

print("NumPy Time =", end-start)


NumPy Time = 0.004681587219238281


**2. Element-wise Multiplication**

Python

In [ ]:
start = time.time()
L4 = [L1[i] * L2[i] for i in range(1_000_000)]
end = time.time()
print("Python Time =", end-start)


Python Time = 0.11260056495666504


NumPy

In [ ]:
start = time.time()
A4 = A1 * A2
end = time.time()
print("NumPy Time =", end-start)


NumPy Time = 0.005931854248046875


**3. Dot Product**

Python

In [ ]:
start = time.time()
dot = sum(L1[i] * L2[i] for i in range(1_000_000))
end = time.time()
print("Python Time =", end-start)


Python Time = 0.10822939872741699


NumPy

In [ ]:
start = time.time()
dot_np = np.dot(A1, A2)
end = time.time()
print("NumPy Time =", end-start)


NumPy Time = 0.0023300647735595703


**4. Matrix Multiplication (1000×1000)**

Python list

In [ ]:
M1 = [[i for i in range(1000)] for j in range(1000)]
M2 = [[i for i in range(1000)] for j in range(1000)]

start = time.time()
M3 = [[sum(a*b for a,b in zip(r,c)) for c in zip(*M2)] for r in M1]
end = time.time()

print("Python Matrix Multiplication Time =", end-start)


KeyboardInterrupt: 

NumPy

In [ ]:
A = np.arange(1_000_000).reshape(1000,1000)
B = np.arange(1_000_000).reshape(1000,1000)

start = time.time()
C = A @ B
end = time.time()

print("NumPy Matrix Multiplication Time =", end-start)


NumPy Matrix Multiplication Time = 2.398606061935425
